### ISSUE TITLE
Books repository | Fix Query Already Executed

### ISSUE THREAD

**Issue by jckoronati** [jckoronati/express-rest#1]
## Possible FIX

Avoid using of callback

https://github.com/jckoronati/express-rest/blob/838251717d05009b399577a8d2afffa3ecc75208/src/Repository/BooksRepository.js#L29-L35

## Trace
```

MongooseError: Query was already executed: books.findOneAndDelete({ _id: new ObjectId("64bd2fb5cc8963c7...
    at model.Query._wrappedThunk [as _findOneAndDelete] (/home/julio/Documentos/projects/express-rest/node_modules/mongoose/lib/helpers/query/wrapThunk.js:21:19)
    at /home/julio/Documentos/projects/express-rest/node_modules/kareem/index.js:372:33
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  originalStack: 'Error\n' +
    '    at model.Query._wrappedThunk [as _findOneAndDelete] (/home/julio/Documentos/projects/express-rest/node_modules/mongoose/lib/helpers/query/wrapThunk.js:25:28)\n' +
    '    at /home/julio/Documentos/projects/express-rest/node_modules/kareem/index.js:372:33\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:78:11)'
}

```

**Comment by jckoronati** [comment]
## Answer

Concluded on: https://github.com/jckoronati/express-rest/commit/fb40234254a07c0ce8e557529fc15b2ffafb7664
